

2024-08-19 20:26:21.049710
20:26:212024-08-19 20:26:21,081 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 20:26:21,095 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 20:26:23,124 - __main__ - DEBUG - [envy.py:66] - server health check status: False
2024-08-19 20:26:23,126 - __main__ - DEBUG - [envy.py:75] - I am the server
2024-08-19 20:26:23,126 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 20:26:23,126 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 20:26:23,126 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 20:26:24,154 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:26:24,155 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:26:24,161 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:26:24,161 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:26:24,164 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:26:24,164 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:26:24,164 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:26:24,164 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:26:24,176 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:26:24,658 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 20:27:45.907498
20:27:452024-08-19 20:27:45,951 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 20:27:45,959 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 20:27:45,967 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 20:27:45,967 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 20:27:45,967 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 20:27:45,967 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 20:27:45,967 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:27:45,968 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:27:45,972 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:27:45,972 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:27:45,974 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:27:45,974 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:27:45,975 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:27:45,975 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:27:45,987 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:27:46,481 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 20:28:46,401 - __main__ - DEBUG - [client.py:171] - consumer_handler: no close frame received or sent
2024-08-19 20:28:47,668 - __main__ - WARNING - [client.py:149] - connection closed with server
2024-08-19 20:28:47,668 - __main__ - DEBUG - [client.py:188] - stopping client
2024-08-19 20:28:47,668 - __main__ - DEBUG - [client.py:98] - disconnecting websocket
2024-08-19 20:28:47,668 - __main__ - DEBUG - [client.py:106] - Connection Closed Successfully
2024-08-19 20:28:47,668 - __main__ - DEBUG - [client.py:199] - cleaning up tasks
2024-08-19 20:28:47,668 - __main__ - DEBUG - [client.py:202] - cancelling task client.consumer_handler
2024-08-19 20:28:47,668 - __main__ - DEBUG - [client.py:212] - client stopped
2024-08-19 20:28:47,668 - __main__ - DEBUG - [envy.py:198] - cleaning up envy.client_dependant_tasks
2024-08-19 20:28:47,669 - __main__ - INFO - [envy.py:214] - electing new server
2024-08-19 20:28:47,669 - __main__ - DEBUG - [envy_utils.py:149] - opening clients file at Z:/school/ENVY/__ENVYTEST__/Connections/clients.json
2024-08-19 20:28:47,682 - __main__ - DEBUG - [envy_utils.py:154] - returning clients: {'lab5-01': {'IP': '10.1.16.22', 'Status': 'idle', 'Job': None, 'Allocation': None}}
2024-08-19 20:28:47,682 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 20:28:47,682 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 20:28:47,715 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:28:48,691 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:28:48,691 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:28:48,704 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:28:48,704 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:28:49,212 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:28:49,212 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:28:49,212 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:28:49,217 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:28:49,450 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 20:36:24.105444
20:36:242024-08-19 20:36:24,151 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 20:36:24,157 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 20:36:24,165 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 20:36:24,165 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 20:36:24,165 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 20:36:24,165 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 20:36:24,165 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:36:24,166 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:36:24,170 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:36:24,170 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:36:24,172 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:36:24,173 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:36:24,173 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:36:24,173 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:36:24,186 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:36:24,667 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 20:36:35,864 - __main__ - DEBUG - [client.py:171] - consumer_handler: no close frame received or sent
2024-08-19 20:36:36,190 - __main__ - WARNING - [client.py:149] - connection closed with server
2024-08-19 20:36:36,190 - __main__ - DEBUG - [client.py:188] - stopping client
2024-08-19 20:36:36,190 - __main__ - DEBUG - [client.py:98] - disconnecting websocket
2024-08-19 20:36:36,190 - __main__ - DEBUG - [client.py:106] - Connection Closed Successfully
2024-08-19 20:36:36,190 - __main__ - DEBUG - [client.py:199] - cleaning up tasks
2024-08-19 20:36:36,190 - __main__ - DEBUG - [client.py:202] - cancelling task client.consumer_handler
2024-08-19 20:36:36,190 - __main__ - DEBUG - [client.py:212] - client stopped
2024-08-19 20:36:36,190 - __main__ - DEBUG - [envy.py:198] - cleaning up envy.client_dependant_tasks
2024-08-19 20:36:36,190 - __main__ - INFO - [envy.py:214] - electing new server
2024-08-19 20:36:36,191 - __main__ - DEBUG - [envy_utils.py:149] - opening clients file at Z:/school/ENVY/__ENVYTEST__/Connections/clients.json
2024-08-19 20:36:36,204 - __main__ - DEBUG - [envy_utils.py:154] - returning clients: {'lab5-01': {'IP': '10.1.16.22', 'Status': 'idle', 'Job': None, 'Allocation': None}}
2024-08-19 20:36:36,204 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 20:36:36,204 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 20:36:36,226 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:36:37,234 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:36:37,234 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:36:37,240 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:36:37,240 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:36:37,758 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:36:37,758 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:36:37,758 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:36:37,763 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:36:37,804 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 20:39:30.386756
20:39:302024-08-19 20:39:30,434 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 20:39:30,440 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 20:39:30,448 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 20:39:30,448 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 20:39:30,448 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 20:39:30,449 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 20:39:30,449 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:39:30,449 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:39:30,453 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:39:30,453 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:39:30,455 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:39:30,455 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:39:30,456 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:39:30,456 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:39:30,469 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:39:30,962 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 20:39:38,709 - __main__ - DEBUG - [client.py:171] - consumer_handler: no close frame received or sent
2024-08-19 20:39:39,485 - __main__ - WARNING - [client.py:149] - connection closed with server
2024-08-19 20:39:39,485 - __main__ - DEBUG - [client.py:188] - stopping client
2024-08-19 20:39:39,485 - __main__ - DEBUG - [client.py:98] - disconnecting websocket
2024-08-19 20:39:39,485 - __main__ - DEBUG - [client.py:106] - Connection Closed Successfully
2024-08-19 20:39:39,485 - __main__ - DEBUG - [client.py:199] - cleaning up tasks
2024-08-19 20:39:39,485 - __main__ - DEBUG - [client.py:202] - cancelling task client.consumer_handler
2024-08-19 20:39:39,485 - __main__ - DEBUG - [client.py:212] - client stopped
2024-08-19 20:39:39,485 - __main__ - DEBUG - [envy.py:198] - cleaning up envy.client_dependant_tasks
2024-08-19 20:39:39,485 - __main__ - INFO - [envy.py:214] - electing new server
2024-08-19 20:39:39,486 - __main__ - DEBUG - [envy_utils.py:149] - opening clients file at Z:/school/ENVY/__ENVYTEST__/Connections/clients.json
2024-08-19 20:39:39,499 - __main__ - DEBUG - [envy_utils.py:154] - returning clients: {'lab5-01': {'IP': '10.1.16.22', 'Status': 'idle', 'Job': None, 'Allocation': None}}
2024-08-19 20:39:39,499 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 20:39:39,500 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 20:39:39,520 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:39:40,529 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:39:40,530 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:39:40,535 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:39:40,535 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:39:40,538 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:39:40,538 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:39:40,538 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:39:40,542 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:39:41,064 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 20:39:42,761 - __main__ - DEBUG - [client.py:171] - consumer_handler: no close frame received or sent
2024-08-19 20:39:43,559 - __main__ - WARNING - [client.py:149] - connection closed with server
2024-08-19 20:39:43,559 - __main__ - DEBUG - [client.py:188] - stopping client
2024-08-19 20:39:43,559 - __main__ - DEBUG - [client.py:98] - disconnecting websocket
2024-08-19 20:39:43,559 - __main__ - DEBUG - [client.py:106] - Connection Closed Successfully
2024-08-19 20:39:43,559 - __main__ - DEBUG - [client.py:199] - cleaning up tasks
2024-08-19 20:39:43,559 - __main__ - DEBUG - [client.py:202] - cancelling task client.producer
2024-08-19 20:39:43,559 - __main__ - DEBUG - [client.py:202] - cancelling task client.producer
2024-08-19 20:39:43,559 - __main__ - DEBUG - [client.py:210] - cancelled task client.producer
2024-08-19 20:39:43,559 - __main__ - DEBUG - [client.py:212] - client stopped
2024-08-19 20:39:43,559 - __main__ - DEBUG - [envy.py:198] - cleaning up envy.client_dependant_tasks
2024-08-19 20:39:43,559 - __main__ - INFO - [envy.py:214] - electing new server
2024-08-19 20:39:43,559 - __main__ - DEBUG - [envy_utils.py:149] - opening clients file at Z:/school/ENVY/__ENVYTEST__/Connections/clients.json
2024-08-19 20:39:43,574 - __main__ - DEBUG - [envy_utils.py:154] - returning clients: {'lab5-01': {'IP': '10.1.16.22', 'Status': 'idle', 'Job': None, 'Allocation': None}}
2024-08-19 20:39:43,574 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 20:39:43,574 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 20:39:44,618 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:39:44,619 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:39:44,624 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:39:44,625 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:39:44,627 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:39:44,627 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:39:44,627 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:39:44,628 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:39:44,632 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:39:45,052 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 20:39:55,146 - __main__ - DEBUG - [client.py:171] - consumer_handler: no close frame received or sent
2024-08-19 20:39:55,186 - __main__ - WARNING - [client.py:149] - connection closed with server
2024-08-19 20:39:55,186 - __main__ - DEBUG - [client.py:188] - stopping client
2024-08-19 20:39:55,186 - __main__ - DEBUG - [client.py:98] - disconnecting websocket
2024-08-19 20:39:55,186 - __main__ - DEBUG - [client.py:106] - Connection Closed Successfully
2024-08-19 20:39:55,186 - __main__ - DEBUG - [client.py:199] - cleaning up tasks
2024-08-19 20:39:55,186 - __main__ - DEBUG - [client.py:202] - cancelling task client.consumer_handler
2024-08-19 20:39:55,186 - __main__ - DEBUG - [client.py:202] - cancelling task client.producer
2024-08-19 20:39:55,186 - __main__ - DEBUG - [client.py:210] - cancelled task client.producer
2024-08-19 20:39:55,186 - __main__ - DEBUG - [client.py:212] - client stopped
2024-08-19 20:39:55,186 - __main__ - DEBUG - [envy.py:198] - cleaning up envy.client_dependant_tasks
2024-08-19 20:39:55,186 - __main__ - INFO - [envy.py:214] - electing new server
2024-08-19 20:39:55,186 - __main__ - DEBUG - [envy_utils.py:149] - opening clients file at Z:/school/ENVY/__ENVYTEST__/Connections/clients.json
2024-08-19 20:39:55,200 - __main__ - DEBUG - [envy_utils.py:154] - returning clients: {'lab5-01': {'IP': '10.1.16.22', 'Status': 'idle', 'Job': None, 'Allocation': None}}
2024-08-19 20:39:55,201 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 20:39:55,201 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 20:39:56,232 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:39:56,232 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:39:56,238 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:39:56,239 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:39:56,241 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:39:56,242 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:39:56,242 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:39:56,242 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:39:56,247 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:39:56,679 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 20:40:05.367583
20:40:052024-08-19 20:40:05,414 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 20:40:05,421 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 20:40:05,426 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 20:40:05,426 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 20:40:05,426 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 20:40:05,426 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 20:40:05,426 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:40:05,427 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:40:05,429 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:40:05,429 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:40:05,431 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:40:05,431 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:40:05,431 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:40:05,431 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:40:05,443 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:40:05,925 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 20:40:49.369858
20:40:492024-08-19 20:40:49,418 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 20:40:49,425 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 20:40:49,432 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 20:40:49,432 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 20:40:49,433 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 20:40:49,433 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 20:40:49,433 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:40:49,433 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:40:49,437 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:40:49,437 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:40:49,439 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:40:49,439 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:40:49,440 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:40:49,440 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:40:49,454 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:40:49,937 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 20:41:43,707 - __main__ - DEBUG - [client.py:171] - consumer_handler: no close frame received or sent
2024-08-19 20:41:45,114 - __main__ - WARNING - [client.py:149] - connection closed with server
2024-08-19 20:41:45,114 - __main__ - DEBUG - [client.py:188] - stopping client
2024-08-19 20:41:45,114 - __main__ - DEBUG - [client.py:98] - disconnecting websocket
2024-08-19 20:41:45,114 - __main__ - DEBUG - [client.py:106] - Connection Closed Successfully
2024-08-19 20:41:45,114 - __main__ - DEBUG - [client.py:199] - cleaning up tasks
2024-08-19 20:41:45,114 - __main__ - DEBUG - [client.py:202] - cancelling task client.consumer_handler
2024-08-19 20:41:45,114 - __main__ - DEBUG - [client.py:212] - client stopped
2024-08-19 20:41:45,114 - __main__ - DEBUG - [envy.py:198] - cleaning up envy.client_dependant_tasks
2024-08-19 20:41:45,114 - __main__ - INFO - [envy.py:214] - electing new server
2024-08-19 20:41:45,114 - __main__ - DEBUG - [envy_utils.py:149] - opening clients file at Z:/school/ENVY/__ENVYTEST__/Connections/clients.json
2024-08-19 20:41:45,128 - __main__ - DEBUG - [envy_utils.py:154] - returning clients: {'lab5-01': {'IP': '10.1.16.22', 'Status': 'idle', 'Job': None, 'Allocation': None}}
2024-08-19 20:41:45,128 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 20:41:45,128 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 20:41:45,242 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:41:46,144 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:41:46,144 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:41:46,157 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:41:46,157 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:41:46,665 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:41:46,665 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:41:46,665 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:41:46,670 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:41:46,849 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 20:41:51,883 - __main__ - DEBUG - [client.py:171] - consumer_handler: no close frame received or sent
2024-08-19 20:41:52,667 - __main__ - WARNING - [client.py:149] - connection closed with server
2024-08-19 20:41:52,667 - __main__ - DEBUG - [client.py:188] - stopping client
2024-08-19 20:41:52,667 - __main__ - DEBUG - [client.py:98] - disconnecting websocket
2024-08-19 20:41:52,667 - __main__ - DEBUG - [client.py:106] - Connection Closed Successfully
2024-08-19 20:41:52,667 - __main__ - DEBUG - [client.py:199] - cleaning up tasks
2024-08-19 20:41:52,667 - __main__ - DEBUG - [client.py:202] - cancelling task client.producer
2024-08-19 20:41:52,667 - __main__ - DEBUG - [client.py:202] - cancelling task client.producer
2024-08-19 20:41:52,667 - __main__ - DEBUG - [client.py:210] - cancelled task client.producer
2024-08-19 20:41:52,667 - __main__ - DEBUG - [client.py:212] - client stopped
2024-08-19 20:41:52,667 - __main__ - DEBUG - [envy.py:198] - cleaning up envy.client_dependant_tasks
2024-08-19 20:41:52,667 - __main__ - INFO - [envy.py:214] - electing new server
2024-08-19 20:41:52,667 - __main__ - DEBUG - [envy_utils.py:149] - opening clients file at Z:/school/ENVY/__ENVYTEST__/Connections/clients.json
2024-08-19 20:41:52,679 - __main__ - DEBUG - [envy_utils.py:154] - returning clients: {'lab5-01': {'IP': '10.1.16.22', 'Status': 'idle', 'Job': None, 'Allocation': None}}
2024-08-19 20:41:52,679 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 20:41:52,679 - __main__ - DEBUG - [envy.py:106] - writing server file


2024-08-19 20:42:12.879696
20:42:122024-08-19 20:42:12,923 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 20:42:12,929 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 20:42:12,934 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 20:42:12,935 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 20:42:12,935 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 20:42:12,935 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 20:42:12,935 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:42:12,936 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:42:12,937 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:42:12,937 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:42:12,939 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:42:12,939 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:42:12,940 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:42:12,940 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:42:12,947 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:42:13,445 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 20:48:46.530287
20:48:462024-08-19 20:48:46,582 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 20:48:46,588 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 20:48:46,595 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 20:48:46,595 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 20:48:46,596 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 20:48:46,596 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 20:48:46,596 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:48:46,597 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:48:46,600 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:48:46,601 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:48:46,602 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:48:46,603 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:48:46,603 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:48:46,603 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:48:46,615 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:48:47,120 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 20:49:53.227878
20:49:532024-08-19 20:49:53,274 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 20:49:53,280 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 20:49:53,288 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 20:49:53,289 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 20:49:53,289 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 20:49:53,289 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 20:49:53,289 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:49:53,290 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:49:53,294 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:49:53,294 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:49:53,296 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:49:53,296 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:49:53,296 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:49:53,296 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:49:53,308 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:49:53,804 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 20:51:33.364082
20:51:332024-08-19 20:51:33,408 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 20:51:33,415 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 20:51:33,421 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 20:51:33,421 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 20:51:33,422 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 20:51:33,422 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 20:51:33,422 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:51:33,423 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:51:33,427 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:51:33,427 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:51:33,428 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:51:33,429 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:51:33,429 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:51:33,429 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:51:33,441 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:51:33,933 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 20:54:18.748401
20:54:182024-08-19 20:54:18,795 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 20:54:18,803 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 20:54:18,810 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 20:54:18,810 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 20:54:18,810 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 20:54:18,810 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 20:54:18,811 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:54:18,811 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:54:18,815 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:54:18,815 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:54:18,817 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:54:18,817 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:54:18,817 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:54:18,817 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:54:18,829 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:54:19,335 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 20:56:40.831191
20:56:402024-08-19 20:56:40,878 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 20:56:40,886 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 20:56:40,893 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 20:56:40,894 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 20:56:40,894 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 20:56:40,894 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 20:56:40,894 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:56:40,895 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:56:40,899 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:56:40,899 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:56:40,900 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:56:40,901 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:56:40,901 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:56:40,902 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:56:40,914 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:56:41,420 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 20:58:20.856289
20:58:202024-08-19 20:58:20,899 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 20:58:20,906 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 20:58:20,914 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 20:58:20,914 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 20:58:20,914 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 20:58:20,914 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 20:58:20,915 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 20:58:20,915 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 20:58:20,919 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 20:58:20,919 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 20:58:20,921 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 20:58:20,921 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 20:58:20,921 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 20:58:20,922 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 20:58:20,934 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 20:58:21,431 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 21:01:10.217404
21:01:102024-08-19 21:01:10,263 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 21:01:10,270 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 21:01:10,277 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 21:01:10,277 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 21:01:10,278 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 21:01:10,278 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 21:01:10,278 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 21:01:10,278 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 21:01:10,283 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 21:01:10,283 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 21:01:10,285 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 21:01:10,285 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 21:01:10,285 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 21:01:10,285 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 21:01:10,297 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 21:01:10,780 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 21:02:37.242411
21:02:372024-08-19 21:02:37,288 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 21:02:37,295 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 21:02:37,301 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 21:02:37,301 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 21:02:37,302 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 21:02:37,302 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 21:02:37,302 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 21:02:37,302 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 21:02:37,307 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 21:02:37,307 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 21:02:37,309 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 21:02:37,309 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 21:02:37,309 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 21:02:37,309 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 21:02:37,321 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 21:02:37,815 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 21:02:42,039 - __main__ - DEBUG - [client.py:171] - consumer_handler: no close frame received or sent
2024-08-19 21:02:43,317 - __main__ - WARNING - [client.py:149] - connection closed with server
2024-08-19 21:02:43,317 - __main__ - DEBUG - [client.py:188] - stopping client
2024-08-19 21:02:43,317 - __main__ - DEBUG - [client.py:98] - disconnecting websocket
2024-08-19 21:02:43,318 - __main__ - DEBUG - [client.py:106] - Connection Closed Successfully
2024-08-19 21:02:43,318 - __main__ - DEBUG - [client.py:199] - cleaning up tasks
2024-08-19 21:02:43,318 - __main__ - DEBUG - [client.py:202] - cancelling task client.consumer_handler
2024-08-19 21:02:43,318 - __main__ - DEBUG - [client.py:212] - client stopped
2024-08-19 21:02:43,318 - __main__ - DEBUG - [envy.py:198] - cleaning up envy.client_dependant_tasks
2024-08-19 21:02:43,318 - __main__ - INFO - [envy.py:214] - electing new server
2024-08-19 21:02:43,319 - __main__ - DEBUG - [envy_utils.py:149] - opening clients file at Z:/school/ENVY/__ENVYTEST__/Connections/clients.json
2024-08-19 21:02:43,330 - __main__ - DEBUG - [envy_utils.py:154] - returning clients: {'lab5-01': {'IP': '10.1.16.22', 'Status': 'idle', 'Job': None, 'Allocation': None}}
2024-08-19 21:02:43,330 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 21:02:43,330 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 21:02:43,365 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 21:02:44,342 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 21:02:44,343 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 21:02:44,349 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 21:02:44,349 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 21:02:44,353 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 21:02:44,353 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 21:02:44,353 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 21:02:44,359 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 21:02:44,862 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 21:09:17.066792
21:09:172024-08-19 21:09:17,115 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 21:09:17,122 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 21:09:17,129 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 21:09:17,129 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 21:09:17,129 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 21:09:17,129 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 21:09:17,129 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 21:09:17,130 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 21:09:17,134 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 21:09:17,134 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 21:09:17,136 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 21:09:17,136 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 21:09:17,137 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 21:09:17,137 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 21:09:17,149 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 21:09:17,652 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 21:10:00.504635
21:10:002024-08-19 21:10:00,546 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 21:10:00,552 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 21:10:00,559 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 21:10:00,559 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 21:10:00,560 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 21:10:00,560 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 21:10:00,560 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 21:10:00,561 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 21:10:00,564 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 21:10:00,565 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 21:10:00,567 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 21:10:00,567 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 21:10:00,567 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 21:10:00,567 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 21:10:00,580 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 21:10:01,076 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 21:10:38.577441
21:10:382024-08-19 21:10:38,626 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 21:10:38,632 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 21:10:38,640 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 21:10:38,640 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 21:10:38,641 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 21:10:38,641 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 21:10:38,641 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 21:10:38,642 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 21:10:38,646 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 21:10:38,646 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 21:10:38,648 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 21:10:38,648 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 21:10:38,648 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 21:10:38,648 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 21:10:38,661 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 21:10:39,155 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 21:10:46,622 - __main__ - DEBUG - [client.py:171] - consumer_handler: no close frame received or sent
2024-08-19 21:10:47,699 - __main__ - WARNING - [client.py:149] - connection closed with server
2024-08-19 21:10:47,699 - __main__ - DEBUG - [client.py:188] - stopping client
2024-08-19 21:10:47,699 - __main__ - DEBUG - [client.py:98] - disconnecting websocket
2024-08-19 21:10:47,699 - __main__ - DEBUG - [client.py:106] - Connection Closed Successfully
2024-08-19 21:10:47,699 - __main__ - DEBUG - [client.py:199] - cleaning up tasks
2024-08-19 21:10:47,699 - __main__ - DEBUG - [client.py:202] - cancelling task client.consumer_handler
2024-08-19 21:10:47,699 - __main__ - DEBUG - [client.py:212] - client stopped
2024-08-19 21:10:47,700 - __main__ - DEBUG - [envy.py:198] - cleaning up envy.client_dependant_tasks
2024-08-19 21:10:47,700 - __main__ - INFO - [envy.py:214] - electing new server
2024-08-19 21:10:47,700 - __main__ - DEBUG - [envy_utils.py:149] - opening clients file at Z:/school/ENVY/__ENVYTEST__/Connections/clients.json
2024-08-19 21:10:47,713 - __main__ - DEBUG - [envy_utils.py:154] - returning clients: {'lab5-01': {'IP': '10.1.16.22', 'Status': 'idle', 'Job': None, 'Allocation': None}}
2024-08-19 21:10:47,713 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 21:10:47,713 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 21:10:47,795 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 21:10:48,739 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 21:10:48,740 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 21:10:48,746 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 21:10:48,746 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 21:10:48,748 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 21:10:48,749 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 21:10:48,749 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 21:10:48,754 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 21:10:49,268 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )


2024-08-19 21:59:00.058233
21:59:002024-08-19 21:59:00,109 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 21:59:00,116 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 21:59:00,124 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 21:59:00,125 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 21:59:00,125 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 21:59:00,125 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 21:59:00,125 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 21:59:00,126 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 21:59:00,130 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 21:59:00,130 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 21:59:00,132 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 21:59:00,132 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 21:59:00,132 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 21:59:00,132 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 21:59:00,145 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 21:59:00,403 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (1, 1, '[1, 2, 3, 4, 5, 6]', 'lab5-01', 'inprogress'))
2024-08-19 21:59:00,639 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 21:59:01,160 - __main__ - DEBUG - [envy.py:257] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 1, "Purpose": "cache", "Tasks": {"1": 1, "2": 2, "3": 3, "4": 4, "5": 5, "6": 6}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-19 21:59:01,227 - __main__ - ERROR - [envy.py:85] - Failed while executing PLUGIN_EXAMPLE(self, '{"Allocation_Id": 1, "Purpose": "cache", "Tasks": {"1": 1, "2": 2, "3": 3, "4": 4, "5": 5, "6": 6}, "Environment": {}, "Parameters": {"A": 5}}', ), [WinError 2] The system cannot find the file specified
2024-08-19 21:59:01,240 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())


2024-08-19 21:59:58.287297
21:59:582024-08-19 21:59:58,332 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 21:59:58,337 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 21:59:58,345 - __main__ - DEBUG - [envy.py:66] - server health check status: True
2024-08-19 21:59:58,345 - __main__ - DEBUG - [envy.py:69] - I am a Client
2024-08-19 21:59:58,345 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 21:59:58,346 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is client
2024-08-19 21:59:58,346 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 21:59:58,347 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 21:59:58,351 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 21:59:58,351 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 21:59:58,353 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 21:59:58,353 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 21:59:58,353 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 21:59:58,354 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 21:59:58,367 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 21:59:58,610 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (2, 1, '[7, 8, 9, 10, 11, 12]', 'lab5-01', 'inprogress'))
2024-08-19 21:59:58,845 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 21:59:59,347 - __main__ - DEBUG - [envy.py:257] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 2, "Purpose": "cache", "Tasks": {"7": 7, "8": 8, "9": 9, "10": 10, "11": 11, "12": 12}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-19 21:59:59,455 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:00:12,588 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task_allocation(): 2)
2024-08-19 22:00:12,588 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:00:12,688 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (3, 1, '[13, 14, 15, 16, 17, 18]', 'lab5-01', 'inprogress'))
2024-08-19 22:00:13,000 - __main__ - DEBUG - [envy.py:257] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 3, "Purpose": "cache", "Tasks": {"13": 13, "14": 14, "15": 15, "16": 16, "17": 17, "18": 18}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-19 22:00:13,007 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:00:26,204 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task_allocation(): 3)
2024-08-19 22:00:26,204 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:00:26,754 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (4, 1, '[19, 20]', 'lab5-01', 'inprogress'))
2024-08-19 22:00:27,135 - __main__ - DEBUG - [envy.py:257] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 4, "Purpose": "cache", "Tasks": {"19": 19, "20": 20}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-19 22:00:27,166 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:00:34,706 - __main__ - DEBUG - [client.py:171] - consumer_handler: no close frame received or sent
2024-08-19 22:00:36,002 - __main__ - WARNING - [client.py:149] - connection closed with server
2024-08-19 22:00:36,002 - __main__ - DEBUG - [client.py:188] - stopping client
2024-08-19 22:00:36,003 - __main__ - DEBUG - [client.py:98] - disconnecting websocket
2024-08-19 22:00:36,003 - __main__ - DEBUG - [client.py:106] - Connection Closed Successfully
2024-08-19 22:00:36,003 - __main__ - DEBUG - [client.py:199] - cleaning up tasks
2024-08-19 22:00:36,004 - __main__ - DEBUG - [client.py:202] - cancelling task client.consumer_handler
2024-08-19 22:00:36,004 - __main__ - DEBUG - [client.py:212] - client stopped
2024-08-19 22:00:36,004 - __main__ - DEBUG - [envy.py:198] - cleaning up envy.client_dependant_tasks
2024-08-19 22:00:36,004 - __main__ - INFO - [envy.py:214] - electing new server
2024-08-19 22:00:36,005 - __main__ - DEBUG - [envy_utils.py:149] - opening clients file at Z:/school/ENVY/__ENVYTEST__/Connections/clients.json
2024-08-19 22:00:36,020 - __main__ - DEBUG - [envy_utils.py:154] - returning clients: {'lab5-01': {'IP': '10.1.16.22', 'Status': 'idle', 'Job': None, 'Allocation': None}}
2024-08-19 22:00:36,020 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 22:00:36,021 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 22:00:36,050 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:00:37,055 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 22:00:37,056 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 22:00:37,069 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 22:00:37,069 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 22:00:38,100 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 22:00:38,101 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 22:00:38,101 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 22:00:38,106 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 22:00:39,910 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (5, 2, '[21, 22, 23, 24, 25, 26]', 'lab5-01', 'inprogress'))
2024-08-19 22:00:40,328 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task_allocation(): 4)
2024-08-19 22:00:40,328 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:00:40,729 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 22:00:41,245 - __main__ - DEBUG - [envy.py:257] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 5, "Purpose": "cache", "Tasks": {"21": 1, "22": 2, "23": 3, "24": 4, "25": 5, "26": 6}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-19 22:00:41,307 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:00:54,359 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task_allocation(): 5)
2024-08-19 22:00:54,359 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:00:55,727 - __main__ - DEBUG - [client.py:171] - consumer_handler: no close frame received or sent
2024-08-19 22:00:56,153 - __main__ - WARNING - [client.py:149] - connection closed with server
2024-08-19 22:00:56,153 - __main__ - DEBUG - [client.py:188] - stopping client
2024-08-19 22:00:56,155 - __main__ - DEBUG - [client.py:98] - disconnecting websocket
2024-08-19 22:00:56,156 - __main__ - DEBUG - [client.py:106] - Connection Closed Successfully
2024-08-19 22:00:56,157 - __main__ - DEBUG - [client.py:199] - cleaning up tasks
2024-08-19 22:00:56,159 - __main__ - DEBUG - [client.py:202] - cancelling task client.producer
2024-08-19 22:00:56,160 - __main__ - DEBUG - [client.py:202] - cancelling task client.producer
2024-08-19 22:00:56,161 - __main__ - DEBUG - [client.py:210] - cancelled task client.producer
2024-08-19 22:00:56,162 - __main__ - DEBUG - [client.py:212] - client stopped
2024-08-19 22:00:56,163 - __main__ - DEBUG - [envy.py:198] - cleaning up envy.client_dependant_tasks
2024-08-19 22:00:56,163 - __main__ - INFO - [envy.py:214] - electing new server
2024-08-19 22:00:56,164 - __main__ - DEBUG - [envy_utils.py:149] - opening clients file at Z:/school/ENVY/__ENVYTEST__/Connections/clients.json
2024-08-19 22:00:56,180 - __main__ - DEBUG - [envy_utils.py:154] - returning clients: {'lab5-01': {'IP': '10.1.16.22', 'Status': 'idle', 'Job': None, 'Allocation': None}}
2024-08-19 22:00:56,180 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 22:00:56,181 - __main__ - DEBUG - [envy.py:106] - writing server file


2024-08-19 22:03:12.273335
22:03:122024-08-19 22:03:12,318 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 22:03:12,329 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 22:03:14,369 - __main__ - DEBUG - [envy.py:66] - server health check status: False
2024-08-19 22:03:14,370 - __main__ - DEBUG - [envy.py:75] - I am the server
2024-08-19 22:03:14,370 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 22:03:14,371 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 22:03:14,371 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 22:03:15,399 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 22:03:15,400 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 22:03:15,406 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 22:03:15,406 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 22:03:15,409 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 22:03:15,409 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 22:03:15,409 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 22:03:15,409 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:03:15,448 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 22:03:15,916 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 22:03:17,380 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (6, 2, '[27, 28, 29, 30, 31, 32]', 'lab5-01', 'inprogress'))
2024-08-19 22:03:17,422 - __main__ - DEBUG - [envy.py:257] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 6, "Purpose": "cache", "Tasks": {"27": 7, "28": 8, "29": 9, "30": 10, "31": 11, "32": 12}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-19 22:03:17,484 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:03:30,579 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task_allocation(): 6)
2024-08-19 22:03:30,579 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:03:31,522 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (7, 2, '[33, 34, 35, 36, 37, 38]', 'lab5-01', 'inprogress'))
2024-08-19 22:03:32,030 - __main__ - DEBUG - [envy.py:257] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 7, "Purpose": "cache", "Tasks": {"33": 13, "34": 14, "35": 15, "36": 16, "37": 17, "38": 18}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-19 22:03:32,097 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:03:45,227 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task_allocation(): 7)
2024-08-19 22:03:45,227 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:03:45,618 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (8, 2, '[39, 40]', 'lab5-01', 'inprogress'))
2024-08-19 22:03:46,133 - __main__ - DEBUG - [envy.py:257] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 8, "Purpose": "cache", "Tasks": {"39": 19, "40": 20}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-19 22:03:46,195 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())


2024-08-19 22:05:12.319331
22:05:122024-08-19 22:05:12,365 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 22:05:12,376 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 22:05:14,416 - __main__ - DEBUG - [envy.py:66] - server health check status: False
2024-08-19 22:05:14,418 - __main__ - DEBUG - [envy.py:75] - I am the server
2024-08-19 22:05:14,418 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 22:05:14,418 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 22:05:14,418 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 22:05:15,449 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 22:05:15,450 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 22:05:15,456 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 22:05:15,456 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 22:05:15,458 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 22:05:15,458 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 22:05:15,459 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 22:05:15,459 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:05:15,472 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 22:05:15,964 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 22:05:33,097 - __main__ - DEBUG - [client.py:171] - consumer_handler: no close frame received or sent
2024-08-19 22:05:33,461 - __main__ - WARNING - [client.py:149] - connection closed with server
2024-08-19 22:05:33,461 - __main__ - DEBUG - [client.py:188] - stopping client
2024-08-19 22:05:33,461 - __main__ - DEBUG - [client.py:98] - disconnecting websocket
2024-08-19 22:05:33,461 - __main__ - DEBUG - [client.py:106] - Connection Closed Successfully
2024-08-19 22:05:33,461 - __main__ - DEBUG - [client.py:199] - cleaning up tasks
2024-08-19 22:05:33,461 - __main__ - DEBUG - [client.py:202] - cancelling task client.consumer_handler
2024-08-19 22:05:33,461 - __main__ - DEBUG - [client.py:212] - client stopped
2024-08-19 22:05:33,462 - __main__ - DEBUG - [envy.py:198] - cleaning up envy.client_dependant_tasks
2024-08-19 22:05:33,462 - __main__ - INFO - [envy.py:214] - electing new server
2024-08-19 22:05:33,462 - __main__ - DEBUG - [envy_utils.py:149] - opening clients file at Z:/school/ENVY/__ENVYTEST__/Connections/clients.json
2024-08-19 22:05:33,474 - __main__ - DEBUG - [envy_utils.py:154] - returning clients: {'lab5-01': {'IP': '10.1.16.22', 'Status': 'idle', 'Job': None, 'Allocation': None}}
2024-08-19 22:05:33,474 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 22:05:33,475 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 22:05:33,507 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:05:34,513 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 22:05:34,513 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 22:05:34,520 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 22:05:34,520 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 22:05:35,031 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 22:05:35,031 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 22:05:35,032 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 22:05:35,036 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 22:05:35,136 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 22:05:37,070 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (1, 1, '[1, 2, 3, 4, 5, 6]', 'lab5-01', 'inprogress'))
2024-08-19 22:05:37,190 - __main__ - DEBUG - [envy.py:257] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 1, "Purpose": "cache", "Tasks": {"1": 1, "2": 2, "3": 3, "4": 4, "5": 5, "6": 6}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-19 22:05:37,284 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:05:50,435 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task_allocation(): 1)
2024-08-19 22:05:50,435 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:05:51,171 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (2, 1, '[7, 8, 9, 10, 11, 12]', 'lab5-01', 'inprogress'))
2024-08-19 22:05:51,348 - __main__ - DEBUG - [envy.py:257] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 2, "Purpose": "cache", "Tasks": {"7": 7, "8": 8, "9": 9, "10": 10, "11": 11, "12": 12}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-19 22:05:51,380 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())


2024-08-19 22:06:49.920933
22:06:492024-08-19 22:06:49,965 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 22:06:49,976 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 22:06:51,996 - __main__ - DEBUG - [envy.py:66] - server health check status: False
2024-08-19 22:06:51,998 - __main__ - DEBUG - [envy.py:75] - I am the server
2024-08-19 22:06:51,998 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 22:06:51,998 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 22:06:51,998 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 22:06:53,020 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 22:06:53,021 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 22:06:53,027 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 22:06:53,027 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 22:06:53,029 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 22:06:53,030 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 22:06:53,030 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 22:06:53,030 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:06:53,043 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 22:06:53,532 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 22:06:54,944 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (3, 1, '[13, 14, 15, 16, 17, 18]', 'lab5-01', 'inprogress'))
2024-08-19 22:06:55,047 - __main__ - DEBUG - [envy.py:257] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 3, "Purpose": "cache", "Tasks": {"13": 13, "14": 14, "15": 15, "16": 16, "17": 17, "18": 18}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-19 22:06:55,111 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())


2024-08-19 22:08:34.468786
22:08:342024-08-19 22:08:34,521 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 22:08:34,531 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 22:08:36,566 - __main__ - DEBUG - [envy.py:66] - server health check status: False
2024-08-19 22:08:36,569 - __main__ - DEBUG - [envy.py:75] - I am the server
2024-08-19 22:08:36,569 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 22:08:36,569 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 22:08:36,569 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 22:08:37,588 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 22:08:37,589 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 22:08:37,596 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 22:08:37,596 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 22:08:37,598 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 22:08:37,598 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 22:08:37,599 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 22:08:37,599 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:08:37,611 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 22:08:38,118 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 22:08:39,534 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (4, 1, '[19, 20]', 'lab5-01', 'inprogress'))
2024-08-19 22:08:39,648 - __main__ - DEBUG - [envy.py:257] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 4, "Purpose": "cache", "Tasks": {"19": 19, "20": 20}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-19 22:08:39,708 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())


2024-08-19 22:09:20.484490
22:09:202024-08-19 22:09:20,533 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 22:09:20,545 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 22:09:22,583 - __main__ - DEBUG - [envy.py:66] - server health check status: False
2024-08-19 22:09:22,585 - __main__ - DEBUG - [envy.py:75] - I am the server
2024-08-19 22:09:22,585 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 22:09:22,585 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 22:09:22,585 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 22:09:23,603 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 22:09:23,604 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 22:09:23,610 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 22:09:23,610 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 22:09:23,613 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 22:09:23,613 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 22:09:23,613 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 22:09:23,613 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:09:23,626 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 22:09:24,121 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 22:09:26,128 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (5, 2, '[21, 22, 23, 24, 25, 26]', 'lab5-01', 'inprogress'))
2024-08-19 22:09:26,159 - __main__ - DEBUG - [envy.py:257] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 5, "Purpose": "cache", "Tasks": {"21": 1, "22": 2, "23": 3, "24": 4, "25": 5, "26": 6}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-19 22:09:26,236 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:09:39,265 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task(): 21)
2024-08-19 22:09:39,265 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task(): 22)
2024-08-19 22:09:39,266 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task(): 23)
2024-08-19 22:09:39,266 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task(): 24)
2024-08-19 22:09:39,266 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task(): 25)
2024-08-19 22:09:39,267 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task(): 26)
2024-08-19 22:09:39,385 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task_allocation(): 5)
2024-08-19 22:09:39,385 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:09:40,271 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (6, 2, '[27, 28, 29, 30, 31, 32]', 'lab5-01', 'inprogress'))
2024-08-19 22:09:40,789 - __main__ - DEBUG - [envy.py:257] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 6, "Purpose": "cache", "Tasks": {"27": 7, "28": 8, "29": 9, "30": 10, "31": 11, "32": 12}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-19 22:09:40,796 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())


2024-08-19 22:11:27.369733
22:11:272024-08-19 22:11:27,413 - __main__ - DEBUG - [envy.py:58] - choosing role
2024-08-19 22:11:27,424 - __main__ - DEBUG - [client.py:39] - health checking server
2024-08-19 22:11:29,457 - __main__ - DEBUG - [envy.py:66] - server health check status: False
2024-08-19 22:11:29,459 - __main__ - DEBUG - [envy.py:75] - I am the server
2024-08-19 22:11:29,459 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 22:11:29,459 - __main__ - DEBUG - [envy.py:149] - envy.connect: Purpose is server
2024-08-19 22:11:29,459 - __main__ - DEBUG - [envy.py:106] - writing server file
2024-08-19 22:11:30,485 - __main__ - DEBUG - [envy_utils.py:95] - getting server IP
2024-08-19 22:11:30,486 - __main__ - DEBUG - [envy_utils.py:107] - server file found
2024-08-19 22:11:30,492 - __main__ - DEBUG - [envy_utils.py:111] - server ip address is: 10.1.16.22
2024-08-19 22:11:30,492 - __main__ - DEBUG - [client.py:53] - attempting to connect with server at ws://10.1.16.22:37020/client
2024-08-19 22:11:30,494 - __main__ - DEBUG - [client.py:133] - networkUtils.client started
2024-08-19 22:11:30,495 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 22:11:30,495 - __main__ - DEBUG - [client.py:157] - connected to: 10.1.16.22
2024-08-19 22:11:30,495 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:11:30,508 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 22:11:31,001 - __main__ - DEBUG - [envy.py:257] - executing: await NV.fill_buffer(self, 'server_name', 'lab5-01', )
2024-08-19 22:11:32,443 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (7, 2, '[33, 34, 35, 36, 37, 38]', 'lab5-01', 'inprogress'))
2024-08-19 22:11:32,529 - __main__ - DEBUG - [envy.py:257] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 7, "Purpose": "cache", "Tasks": {"33": 13, "34": 14, "35": 15, "36": 16, "37": 17, "38": 18}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-19 22:11:32,558 - __main__ - DEBUG - [client.py:115] - sending message to server: (send_status_to_server())
2024-08-19 22:11:45,677 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task(): 33)
2024-08-19 22:11:58,765 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task(): 34)
2024-08-19 22:12:11,682 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task(): 35)
2024-08-19 22:12:24,768 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task(): 36)
2024-08-19 22:12:37,780 - __main__ - DEBUG - [client.py:115] - sending message to server: (finish_task(): 37)


2024-08-19 22:13:59.851367
22:13:592024-08-19 22:14:01,926 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 22:14:02,971 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 22:14:02,982 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))


2024-08-19 22:14:15.839113
22:14:152024-08-19 22:14:17,935 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 22:14:18,974 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 22:14:18,987 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 22:14:21,275 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (1, 1, '[1, 2, 3, 4, 5, 6]', 'lab5-01', 'inprogress'))


2024-08-19 22:15:25.874583
22:15:252024-08-19 22:15:27,978 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 22:15:29,005 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 22:15:29,016 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))


2024-08-19 22:16:42.195175
22:16:422024-08-19 22:16:44,292 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 22:16:45,347 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 22:16:45,359 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 22:16:47,151 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (1, 1, '[1, 2, 3]', 'lab5-01', 'inprogress'))
2024-08-19 22:17:27,396 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (2, 1, '[4, 5, 6]', 'lab5-01', 'inprogress'))


2024-08-19 22:19:12.674261
22:19:122024-08-19 22:19:14,794 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 22:19:15,823 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 22:19:15,836 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 22:19:17,766 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (3, 1, '[7, 8, 9]', 'lab5-01', 'inprogress'))
2024-08-19 22:19:57,918 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (4, 1, '[10]', 'lab5-01', 'inprogress'))
2024-08-19 22:20:11,987 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (5, 2, '[11, 12, 13]', 'lab5-01', 'inprogress'))


2024-08-19 22:34:28.660687
22:34:282024-08-19 22:34:30,764 - __main__ - INFO - [envy.py:128] - Started Envy
2024-08-19 22:34:31,792 - __main__ - INFO - [client.py:145] - Client: Connected
2024-08-19 22:34:31,803 - __main__ - INFO - [client.py:162] - received message from: server -> (fill_buffer(self, 'server_name', 'lab5-01', ))
2024-08-19 22:34:33,747 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (6, 2, '[14, 15, 16]', 'lab5-01', 'inprogress'))
2024-08-19 22:35:13,989 - __main__ - INFO - [client.py:162] - received message from: server -> (Job: something_else Allocation: (7, 2, '[17, 18, 19]', 'lab5-01', 'inprogress'))
