

2024-08-28 19:02:10.954555
19:02:102024-08-28 19:02:11,021 - __main__ - DEBUG - [envy.py:62] - choosing role
2024-08-28 19:02:11,030 - __main__ - DEBUG - [client.py:40] - health checking server
2024-08-28 19:02:11,035 - __main__ - DEBUG - [envy.py:70] - server health check status: True
2024-08-28 19:02:11,035 - __main__ - DEBUG - [envy.py:73] - I am a Client
2024-08-28 19:02:11,035 - __main__ - INFO - [envy.py:132] - Started Envy
2024-08-28 19:02:11,036 - __main__ - DEBUG - [envy.py:153] - envy.connect: Purpose is client
2024-08-28 19:02:11,036 - __main__ - DEBUG - [envy_utils.py:93] - getting server IP
2024-08-28 19:02:11,036 - __main__ - DEBUG - [envy_utils.py:105] - server file found
2024-08-28 19:02:11,039 - __main__ - DEBUG - [envy_utils.py:109] - server ip address is: 10.1.16.14
2024-08-28 19:02:11,039 - __main__ - DEBUG - [client.py:54] - attempting to connect with server at ws://10.1.16.14:37020/client
2024-08-28 19:02:11,041 - __main__ - DEBUG - [client.py:141] - networkUtils.client started
2024-08-28 19:02:11,041 - __main__ - INFO - [client.py:153] - Client: Connected
2024-08-28 19:02:11,041 - __main__ - DEBUG - [client.py:165] - connected to: 10.1.16.14
2024-08-28 19:02:11,087 - __main__ - DEBUG - [client.py:123] - sending message to server: (send_status_to_server())
2024-08-28 19:02:11,087 - __main__ - INFO - [client.py:170] - received message from: server -> (fill_buffer(self, 'server_name', 'lab6-05', ))
2024-08-28 19:02:11,148 - __main__ - DEBUG - [envy.py:265] - executing: await NV.fill_buffer(self, 'server_name', 'lab6-05', )
2024-08-28 19:02:22,560 - __main__ - INFO - [client.py:170] - received message from: server -> (Job: something_else Allocation: (103, 6393620766, '[606, 607, 608, 609, 610]', 'lab6-06', 'inprogress'))
2024-08-28 19:02:22,598 - __main__ - DEBUG - [envy.py:265] - executing: await NV.PLUGIN_EXAMPLE(self, '{"Allocation_Id": 103, "Purpose": "cache", "Tasks": {"606": 6, "607": 7, "608": 8, "609": 9, "610": 10}, "Environment": {}, "Parameters": {"A": 5}}', )
2024-08-28 19:02:22,703 - __main__ - DEBUG - [client.py:123] - sending message to server: (send_status_to_server())
2024-08-28 19:02:22,770 - __main__ - DEBUG - [client.py:123] - sending message to server: (start_task(): 606)
2024-08-28 19:02:35,767 - __main__ - DEBUG - [client.py:123] - sending message to server: (finish_task(): 606)
2024-08-28 19:02:35,829 - __main__ - DEBUG - [client.py:123] - sending message to server: (start_task(): 607)
2024-08-28 19:02:48,800 - __main__ - DEBUG - [client.py:123] - sending message to server: (finish_task(): 607)
2024-08-28 19:02:48,861 - __main__ - DEBUG - [client.py:123] - sending message to server: (start_task(): 608)
2024-08-28 19:03:01,765 - __main__ - DEBUG - [client.py:123] - sending message to server: (finish_task(): 608)
2024-08-28 19:03:01,827 - __main__ - DEBUG - [client.py:123] - sending message to server: (start_task(): 609)
2024-08-28 19:03:06,068 - __main__ - INFO - [client.py:170] - received message from: server -> (Stop_Working -> lab6-06)
2024-08-28 19:03:06,175 - __main__ - DEBUG - [envy.py:265] - executing: await NV.stop_working(self, False, )
2024-08-28 19:03:06,285 - __main__ - DEBUG - [client.py:123] - sending message to server: (send_status_to_server())
2024-08-28 19:03:06,347 - __main__ - DEBUG - [client.py:123] - sending message to server: (finish_task_allocation(): 103)
2024-08-28 19:03:06,348 - __main__ - INFO - [client.py:170] - received message from: server -> (Stop_Working -> lab6-06)
2024-08-28 19:03:06,394 - __main__ - DEBUG - [client.py:123] - sending message to server: (send_status_to_server())
2024-08-28 19:03:06,394 - __main__ - DEBUG - [envy.py:265] - executing: await NV.stop_working(self, False, )
2024-08-28 19:03:06,455 - __main__ - DEBUG - [client.py:123] - sending message to server: (send_status_to_server())
2024-08-28 19:03:11,277 - __main__ - DEBUG - [client.py:123] - sending message to server: (send_status_to_server())
2024-08-28 19:03:11,449 - __main__ - DEBUG - [client.py:123] - sending message to server: (send_status_to_server())
2024-08-28 19:04:20,305 - __main__ - INFO - [client.py:170] - received message from: server -> (restart_envy())
2024-08-28 19:04:20,355 - __main__ - DEBUG - [envy.py:265] - executing: await NV.restart_envy(self, )
2024-08-28 19:04:20,355 - __main__ - DEBUG - [envy.py:277] - envy: exiting


2024-08-28 19:04:21.534389
19:04:212024-08-28 19:04:21,599 - __main__ - DEBUG - [envy.py:62] - choosing role
2024-08-28 19:04:21,609 - __main__ - DEBUG - [client.py:40] - health checking server
2024-08-28 19:04:24,631 - __main__ - DEBUG - [envy.py:70] - server health check status: True
2024-08-28 19:04:24,631 - __main__ - DEBUG - [envy.py:73] - I am a Client
2024-08-28 19:04:24,631 - __main__ - INFO - [envy.py:132] - Started Envy
2024-08-28 19:04:24,631 - __main__ - DEBUG - [envy.py:153] - envy.connect: Purpose is client
2024-08-28 19:04:24,631 - __main__ - DEBUG - [envy_utils.py:93] - getting server IP
2024-08-28 19:04:24,633 - __main__ - DEBUG - [envy_utils.py:105] - server file found
2024-08-28 19:04:24,640 - __main__ - DEBUG - [envy_utils.py:109] - server ip address is: 10.1.16.14
2024-08-28 19:04:24,640 - __main__ - DEBUG - [client.py:54] - attempting to connect with server at ws://10.1.16.14:37020/client
2024-08-28 19:04:24,642 - __main__ - DEBUG - [client.py:141] - networkUtils.client started
2024-08-28 19:04:24,642 - __main__ - INFO - [client.py:153] - Client: Connected
2024-08-28 19:04:24,642 - __main__ - DEBUG - [client.py:165] - connected to: 10.1.16.14
2024-08-28 19:04:24,694 - __main__ - DEBUG - [client.py:123] - sending message to server: (send_status_to_server())
2024-08-28 19:04:24,694 - __main__ - INFO - [client.py:170] - received message from: server -> (fill_buffer(self, 'server_name', 'lab6-05', ))
2024-08-28 19:04:24,753 - __main__ - DEBUG - [envy.py:265] - executing: await NV.fill_buffer(self, 'server_name', 'lab6-05', )
2024-08-28 19:05:16,114 - __main__ - INFO - [client.py:170] - received message from: server -> (sign_out())
2024-08-28 19:05:16,197 - __main__ - DEBUG - [envy.py:265] - executing: await NV.sign_out(self, )


2024-08-28 21:46:21.721175
21:46:212024-08-28 21:46:21,778 - __main__ - DEBUG - [envy.py:62] - choosing role
2024-08-28 21:46:21,786 - __main__ - DEBUG - [client.py:40] - health checking server
2024-08-28 21:46:21,790 - __main__ - DEBUG - [envy.py:70] - server health check status: True
2024-08-28 21:46:21,790 - __main__ - DEBUG - [envy.py:73] - I am a Client
2024-08-28 21:46:21,790 - __main__ - INFO - [envy.py:132] - Started Envy
2024-08-28 21:46:21,790 - __main__ - DEBUG - [envy.py:153] - envy.connect: Purpose is client
2024-08-28 21:46:21,791 - __main__ - DEBUG - [envy_utils.py:93] - getting server IP
2024-08-28 21:46:21,792 - __main__ - DEBUG - [envy_utils.py:105] - server file found
2024-08-28 21:46:21,793 - __main__ - DEBUG - [envy_utils.py:109] - server ip address is: 10.1.16.14
2024-08-28 21:46:21,793 - __main__ - DEBUG - [client.py:54] - attempting to connect with server at ws://10.1.16.14:37020/client
2024-08-28 21:46:21,795 - __main__ - DEBUG - [client.py:141] - networkUtils.client started
2024-08-28 21:46:21,795 - __main__ - INFO - [client.py:153] - Client: Connected
2024-08-28 21:46:21,795 - __main__ - DEBUG - [client.py:165] - connected to: 10.1.16.14
2024-08-28 21:46:21,838 - __main__ - DEBUG - [client.py:123] - sending message to server: (send_status_to_server())
2024-08-28 21:46:21,838 - __main__ - INFO - [client.py:170] - received message from: server -> (fill_buffer(self, 'server_name', 'lab6-05', ))
2024-08-28 21:46:21,900 - __main__ - DEBUG - [envy.py:265] - executing: await NV.fill_buffer(self, 'server_name', 'lab6-05', )
2024-08-28 23:01:23,500 - __main__ - DEBUG - [client.py:179] - consumer_handler: no close frame received or sent
2024-08-28 23:01:24,526 - __main__ - WARNING - [client.py:157] - connection closed with server
2024-08-28 23:01:24,526 - __main__ - DEBUG - [client.py:196] - stopping client
2024-08-28 23:01:24,527 - __main__ - DEBUG - [client.py:105] - disconnecting websocket
2024-08-28 23:01:24,527 - __main__ - DEBUG - [client.py:113] - Connection Closed Successfully
2024-08-28 23:01:24,527 - __main__ - DEBUG - [client.py:207] - cleaning up tasks
2024-08-28 23:01:24,527 - __main__ - DEBUG - [client.py:210] - cancelling task client.consumer_handler
2024-08-28 23:01:24,528 - __main__ - DEBUG - [client.py:220] - client stopped
2024-08-28 23:01:24,528 - __main__ - DEBUG - [envy.py:202] - cleaning up envy.client_dependant_tasks
2024-08-28 23:01:24,528 - __main__ - INFO - [envy.py:218] - electing new server
2024-08-28 23:01:24,528 - __main__ - DEBUG - [envy_utils.py:147] - opening clients file at Z:/school/envy_repo/__envytest__/Connections/clients.json
2024-08-28 23:01:24,546 - __main__ - DEBUG - [envy_utils.py:152] - returning clients: {'lab6-05': {'IP': '10.1.16.14', 'Status': 'idle', 'Job': 4348137846, 'Allocation': 392}, 'lab6-06': {'IP': '10.1.16.15', 'Status': 'idle', 'Job': None, 'Allocation': None}}
2024-08-28 23:01:24,547 - __main__ - DEBUG - [envy.py:226] - removing old server from eligible clients
2024-08-28 23:01:24,547 - __main__ - DEBUG - [envy.py:232] - New server: lab6-06
2024-08-28 23:01:24,548 - __main__ - DEBUG - [envy.py:153] - envy.connect: Purpose is server
2024-08-28 23:01:24,548 - __main__ - DEBUG - [envy.py:109] - writing server file
2024-08-28 23:01:24,563 - __main__ - DEBUG - [client.py:123] - sending message to server: (send_status_to_server())
2024-08-28 23:01:25,568 - __main__ - DEBUG - [envy_utils.py:93] - getting server IP
2024-08-28 23:01:25,568 - __main__ - DEBUG - [envy_utils.py:105] - server file found
2024-08-28 23:01:25,582 - __main__ - DEBUG - [envy_utils.py:109] - server ip address is: 10.1.16.14
2024-08-28 23:01:25,582 - __main__ - DEBUG - [client.py:54] - attempting to connect with server at ws://10.1.16.14:37020/client
2024-08-28 23:01:35,599 - __main__ - INFO - [envy.py:160] - Failed to connect to server
2024-08-28 23:01:35,599 - __main__ - INFO - [envy.py:164] - Failed to connect because of timeout
2024-08-28 23:01:35,600 - __main__ - DEBUG - [envy.py:165] - Info: , exception type: <class 'TimeoutError'>
2024-08-28 23:01:35,600 - __main__ - INFO - [envy.py:218] - electing new server
2024-08-28 23:01:35,600 - __main__ - DEBUG - [envy_utils.py:147] - opening clients file at Z:/school/envy_repo/__envytest__/Connections/clients.json
2024-08-28 23:01:35,607 - __main__ - DEBUG - [envy_utils.py:152] - returning clients: {'lab6-05': {'IP': '10.1.16.14', 'Status': 'idle', 'Job': 4348137846, 'Allocation': 392}, 'lab6-06': {'IP': '10.1.16.15', 'Status': 'idle', 'Job': None, 'Allocation': None}}
2024-08-28 23:01:35,607 - __main__ - DEBUG - [envy.py:226] - removing old server from eligible clients
2024-08-28 23:01:35,607 - __main__ - DEBUG - [envy.py:232] - New server: lab6-06
2024-08-28 23:01:35,608 - __main__ - DEBUG - [envy.py:153] - envy.connect: Purpose is server
2024-08-28 23:01:35,608 - __main__ - DEBUG - [envy.py:109] - writing server file
2024-08-28 23:01:35,608 - __main__ - DEBUG - [envy_utils.py:93] - getting server IP
2024-08-28 23:01:35,610 - __main__ - DEBUG - [envy_utils.py:105] - server file found
2024-08-28 23:01:35,616 - __main__ - DEBUG - [envy_utils.py:109] - server ip address is: 10.1.16.15
2024-08-28 23:01:35,616 - __main__ - DEBUG - [client.py:54] - attempting to connect with server at ws://10.1.16.15:37020/client
2024-08-28 23:01:35,619 - __main__ - DEBUG - [client.py:141] - networkUtils.client started
2024-08-28 23:01:35,619 - __main__ - INFO - [client.py:153] - Client: Connected
2024-08-28 23:01:35,619 - __main__ - DEBUG - [client.py:165] - connected to: 10.1.16.15
2024-08-28 23:01:35,625 - __main__ - INFO - [client.py:170] - received message from: server -> (fill_buffer(self, 'server_name', 'lab6-06', ))
2024-08-28 23:01:35,691 - __main__ - DEBUG - [client.py:123] - sending message to server: (send_status_to_server())
2024-08-28 23:01:35,722 - __main__ - DEBUG - [envy.py:265] - executing: await NV.fill_buffer(self, 'server_name', 'lab6-06', )
